# Generated by Django 3.1.3 on 2020-11-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0003_infos'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='C_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
