# Generated by Django 3.1.3 on 2020-11-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0004_customer_c_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='C_id',
            new_name='Cid',
        ),
    ]
