# Generated by Django 3.1.3 on 2020-11-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0005_auto_20201129_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Cid',
            new_name='C_id',
        ),
    ]
